NEG.Module("NEG.Widget.PropertyManager.Model",function(){var n={BEFORE_PROPERTY_INIT:"Widget_PropertyManager_Model_Before_Property_Init",AFTER_PROPERTY_INIT:"Widget_PropertyManager_Model_After_Property_Init",BEFORE_PROPERTY_CHANGE:"Widget_PropertyManager_Model_Before_Property_Change",AFTER_PROPERTY_CHANGE:"Widget_PropertyManager_Model_After_Property_Change"},q=function(d){var c=[];if(d)for(var g=d.length,h=0;h<g;h++)c.push(d[h]);return c},t=function(d){var c=[];if(d&&0<d.length)for(var g=d.length,
h=0;h<g;h++){var i={exclude:d[h].name,include:[]},e;for(e=0;e<h;e++)i.include.push(d[e]);for(e=h+1;e<g;e++)i.include.push(d[e]);c.push(i)}return c},u=function(d,c){var g=[];if(d&&0<d.length)for(var h=d.length,i=0;i<h;i++){var e=d[i];c[e.name][e.value]&&g.push(e)}return g},v=function(d){var c=this,g={},h=[],i=[],e=[],k=[],r=function(a){var b={resultInfo:[],propertyStatus:[]},j=m(a),l=function(){for(var a=NEG.cast([]),b=j.length,d=0;d<b;d++)a.addRange(j[d].map);return a.source}();b.resultInfo=function(){for(var a=
[],b=j.length,d=0;d<b;d++)a.push(j[d].info);return a}();for(var a=t(a),f=a.length,s=[],c=0;c<f;c++)for(var e=a[c],i=m(e.include),h=i.length,k=0;k<h;k++)for(var r=NEG.cast([]),o=i[k].map,n=o.length,q=0;q<n;q++){var p=o[q];p.name==e.exclude&&-1==r.indexOf(p.value)&&(s.push(p),r.push(p.value))}a=function(){var a=NEG.cast([]);if(0==s.length)for(var b=d.availableMap.length,j=0;j<b;j++)a.addRange(d.availableMap[j].map);else a.addRange(s),a.addRange(l);a=a.source;for(b=[];0<a.length;){for(var j=a[0],f=b.length,
c=!0,g=0;g<f;g++){var e=b[g];if(e.name==j.name&&e.value==j.value){c=!1;break}}c&&b.push(j);a.splice(0,1)}return b}();b.propertyStatus=u(a,g);return b},m=function(a){var b;if(a&&0<a.length){b=[];for(var j=a.length,l=0;l<j;l++){var f,c=g[a[l].name];c&&(f=c[a[l].value]);f&&b.push(f)}if(0<b.length){j=b.length;l=b[0].length;a=0;for(f=1;f<j;f++)if(b[f].length<l)l=b[f].length,a=f;j=b[a];b.splice(a,1);for(a=j;0<b.length;){l=b.length;f=b[0].length;j=0;for(c=1;c<l;c++)if(b[c].length<f)f=b[c].length,j=c;l=[];
f=b[j];for(var c=a.length,e=0;e<c;e++)for(var i=f.length,h=0;h<i;h++)a[e]===f[h]&&l.push(a[e]);a=l;b.splice(j,1)}b=a}}else b=d.availableMap;return b},p=function(a){i=q(a);a=r(a);e=a.propertyStatus;k=a.resultInfo},o=function(a){return{resultInfo:q(k),propertyStatus:q(e),selectedProperty:q(i),target:a?a.target:null}};this.init=function(a,b){("undefined"==typeof b||b)&&NEG(c).trigger(n.BEFORE_PROPERTY_INIT,o(a));p(a);("undefined"==typeof b||b)&&NEG(c).trigger(n.AFTER_PROPERTY_INIT,o(a))};this.changeProperty=
function(a,b){("undefined"==typeof b||b)&&NEG(c).trigger(n.BEFORE_PROPERTY_CHANGE,o(a));p(a);("undefined"==typeof b||b)&&NEG(c).trigger(n.AFTER_PROPERTY_CHANGE,o(a))};this.on=function(a,b){var d=n[a];if(d&&b)NEG(c).on(d,b)};this.off=function(a,b){var d=n[a];d&&b&&NEG(c).off(d,b)};this.searchInInfos=function(a){for(var b=[],c=d.availableMap.length,l=0;l<c;l++){var f=d.availableMap[l];a(f.info)&&b.push(f.map)}return b};this.searchInfosByProperty=function(a){var b=null;if(NEG.utility.isDefined(a)&&NEG.utility.isDefined(a.name)&&
NEG.utility.isDefined(a.value)&&(b=[],a=m([a]),0<a.length))for(var d=a.length,c=0;c<d;c++)b.push(a[c].info);return b};(function(){for(var a=d.properties.length,b=0;b<a;b++){var c=d.properties[b],e=c.name,f=g[e];e&&!NEG.utility.isDefined(f)&&(f=g[e]={});for(var i=c.value.length,e=0;e<i;e++)f[c.value[e]]=[]}a=d.availableMap.length;for(e=0;e<a;e++){b=d.availableMap[e];c=b.map.length;f=!0;for(i=0;i<c;i++){var k=b.map[i],m=g[k.name];if(!m||!m[k.value]){f=!1;break}}if(f){for(f=0;f<c;f++)k=b.map[f],i=g[k.name],
k=i[k.value],i&&k&&k.push(b);h.push(b.info)}}})()},w=function(d){var c={},g=[];c.properties=function(){for(var c=[],e=d.properties.length,k=0;k<e;k++){var h=d.properties[k],m={};m.name=h.name;m.value=h.value;g.push(m.name);c.push(m)}return c}();var h=NEG.cast(g);c.availableMap=function(){for(var c=[],e=d.availableMap.length,g=0;g<e;g++){for(var n=d.availableMap[g],m=!0,p=n.map.length,o=[],a=0;a<p;a++){var b=n.map[a].name;if(!b||-1==h.indexOf(b)||-1!=NEG.cast(o).indexOf(b)){m=!1;break}o.push(b)}m&&
c.push(n)}return c}();return c};return function(d,c){var g=null;NEG.utility.isDefined(d.properties)&&0<d.properties.length&&NEG.utility.isDefined(d.availableMap)&&0<d.availableMap.length&&(g=w(d),g=new v(g,c));return g}});
