/* SimilaritiesUDPTransistionAssets */
(function(b){b.execute(function(){b.when("A","twisterModule").execute("sims-bind-twister",function(d){var b=window.DetailPageFramework;b&&d.each(["session-similarities","purchase-similarities","buyxgety"],function(f){var g=["sims",f,"twister"].join(":");b.registerCallback("asin_select",f,function(){d.trigger(g,"asin_select")});b.registerCallback("after_redraw",f,function(){d.trigger(g,"after_redraw")})})})})})(function(){var b=window.AmazonUIPageJS||P,d=b.attributeErrors;return d?d("SimilaritiesUDPTransistionAssets"):
b}());
;/* BeautyRecommendationAssets */
(function(e){e.execute(function(){e.when("jQuery","cf").register("beauty-recommendations-cf",function(a){function c(d,b){for(var s="bRec"+(d?"Vert":"Horiz")+"ImgHolder",g,c,e=0;e<f;e++)g=s+e,g=a("#"+g),c=a("#bRecImg"+e),b?n(c,b[e],g):c.detach().appendTo(g)}function e(d){for(var d="bRec"+(d?"Vert":"Horiz")+"CheckHolder",b,c,g=0;g<f;g++)b=d+g,b=a("#"+b),c=a("#bRecCheckOuter"+g),c.detach().appendTo(b)}function j(a,d){var b,c;b=d.offset();c=a.offset();return{top:c.top-b.top,left:c.left-b.left}}function n(a,
d,c){a.css("left",d.left);a.css("top",d.top);a.css("position","absolute");a.detach().appendTo(b);setTimeout(function(){var d=j(c,b);a.animate({left:d.left,top:d.top},250,"swing")},1);setTimeout(function(){a.detach().appendTo(c);a.css("position","static")},400)}function m(){for(var d,c=[],e=0;e<f;e++)d=a("#bRecImg"+e),d=j(d,b),c.push(d);return c}var f,b,h,k,d,q,l,i;return{init:function(){f=a(".bRecVerticalContent").length;b=a("#beautyRecommendations");h=a("#bRecHorizontalView");k=a("#bRecVerticalView");
d=a("#bRecToggle");q=a("#useWithDot");l=!0;i=!1;if(f>1){k.hide();l=!1;h.show();i=!0;c(!1,null);e(!1);for(var j=0;j<f;j++)a("#bRecCheckbox"+j).prop("checked",!0);d.css("visibility","visible");d.click(function(d){a.get(a(this).data("foresterurl"));var b=m();i?(h.hide(),i=!1,k.fadeIn(400,function(){l=!0}),c(!0,b),e(!0)):l&&(k.hide(),l=!1,h.fadeIn(400,function(){i=!0}),c(!1,b),e(!1));d.preventDefault()});q.click(function(){d.click()})}}}});e.when("A","jQuery","ready").register("beauty-recommendations-ready",
function(a,c){function e(a){switch(a){case 0:return b.bRecCart1;case 1:return b.bRecCart2;case 2:return b.bRecCart3;case 3:return b.bRecCart4;default:return b.bRecCart1}}function j(a){switch(a){case 0:return b.bRecWish1;case 1:return b.bRecWish2;case 2:return b.bRecWish3;case 3:return b.bRecWish4;default:return b.bRecWish1}}function n(a){switch(a){case 0:return b.bRecPrice1;case 1:return b.bRecPrice2;case 2:return b.bRecPrice3;case 3:return b.bRecPrice4;default:return b.bRecPrice1}}function m(){for(var a=
0,b,f,i=0;i<h;i++)f=c("#bRecImg"+i),(b=c("#bRecCheckbox"+i).prop("checked"))?(a++,f.removeClass("bRecDisabled")):f.addClass("bRecDisabled");c("#bRecAddToCart").find("span.a-button-text").text(e(a));c("#bRecAddToList").find("span.a-button-text").text(j(a));c("#bRecPriceLabel").text(n(a));a="";for(b=0;b<h;b++)a+=c("#bRecCheckbox"+b).prop("checked")?"1":"0";a=parseInt(a,2);a=k[a];c("#bRecPrice").text(a)}var f,b,h,k;return{init:function(){var d=c("#bRecDataDiv").find("script").html();f=d?c.parseJSON(d):
a.state("beautyRecommendations");b=a.state("bRecDynamicStrings");if(f){h=f.numRecommendations;k=f.possibleSums;for(d=0;d<h;d++)c("#bRecCheckbox"+d).change(m);c("#bRecPricePara").removeClass("a-hidden");m()}}}})})})(function(){var e=window.AmazonUIPageJS||P,a=e.attributeErrors;return a?a("BeautyRecommendationAssets"):e}());
;/* ProductAdsDetailPageAssets */
(function(a){a.execute(function(){})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("ProductAdsDetailPageAssets"):a}());
;/* CommonDetailPageScripts */
(function(g){g.execute(function(){g.when("jQuery","jumpLink").execute(function(g,a){var k=g("#miniATFUDP"),e=0;k.length>0&&(e=k.height()+9);window.isACRJumplLinkAnimated===1?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",1E3,e):window.isACRJumplLinkAnimated===2?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",1200,e):window.isACRJumplLinkAnimated===3?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",
1400,e):window.isACRJumplLinkAnimated===4?a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",10,e):k.length>0&&(e=k.height()+9,a.bind("#acrCustomerWriteReviewLink, #acrCustomerReviewLink, #reviewLink, #reviewLinkShort, #reviewCreateLink",10,e))});g.when("A","jQuery","ImageBlockATF","jumpLink").register("miniATFUtils",function(j,a,k,e){function t(d){n&&!d||o||(d=(new Date).getTime()-u,d=d<50?50-d:10,n=1,n=0,u=(new Date).getTime(),setTimeout(function(){var d=
l.scrollTop(),e=a("#miniATFUDP");if(e.length>0){var c=v;if(c==="T1"){c=a("#sims_fbt");if(c.length<=0||c.height()<=0)c=a("#buyxgety_feature_div");var f=c,c=Number.MAX_VALUE;if(f&&f.length>0){var i=f.height(),f=f.offset();i&&f&&(c=f.top+i)}c=Math.min(c,w)}else if(c==="T2"){c="#product-details-grid_feature_div,#prodDetails,#important-information_feature_div,#importantInformation,#detail-bullets,#detail_bullets_id,#technical-data,#technicalSpecifications_feature_div,#productDescription,#product-description-iframe,#dpx-btf-hlcx-comparison_feature_div,#HLCXComparisonWidget_feature_div".split(",");
f=Number.MAX_VALUE;for(i=0;i<c.length;i++){var h=a(c[i]);if(h&&h.length>0&&h.height()>0){var b;b=Number.MAX_VALUE;if(h&&h.length>0&&(h=h.offset()))b=h.top;b<f&&(f=b)}}c=Math.min(f,x)-100}else c=void 0;d>c?!p&&e.is(":hidden")&&(e.removeClass("a-hidden"),e.slideDown(y)):(e.slideUp(z),p=0)}},d))}var q=a("#miniATFUDP");if(!(q.length<=0)){var l,p=0,u=0,n=0,m={},o=0,z=200,y=200,w=1200,x=1700,r=0,v="T1";m.setMiniATFShowHeight=function(d){v=d};m.setMiniATFScrollUpHeight=function(d){r=0;d==="T1"&&(d=a("#productTitle"),
d.length>0&&(d=d.offset())&&(r=d.top-20))};a("body").delegate(".go-to-top","click",function(){a("body, html").animate({scrollTop:r},300);p=1;return!1});l=a(window);l.scroll(function(){t(0)});l.resize(function(){t(1)});var s=0;q.length>0&&(s=q.height()+9,e.bind("#seeMoreDetailsLink",300,s),e.bind("#HLCXComparisonJumplinkLink",300,s));g.when("ImageBlockBTF","imageBlockUtils").execute(function(d){var e=function(b){var c=b.getState().selected_variations;if(c){var e="",g=b.getState().variation_display_labels;
a.each(d.visualDimensions,function(b,a){var f=d.gIsNewTwister===1?a:g[a];c[f]&&(e+=" "+c[f])});return e&&e.substring(1)}},g=d.defaultColor,c=g,f=d.landingAsinColor,i,h=a("#miniATF_image");h.length>0&&(i=h.attr("src"));m.updateMiniATFDiv=function(){o=0;var b=a("#miniATF_image");b.length>0&&i&&b.attr("src",i)};j.on("image-block-twister-swatch-click",function(b,a,h,j){o=1;b=(b=j?j:e(a))&&b!==""?b:g;b===f&&(b=g);b!==c&&(i=(a=b!==g&&b!==f?d:k)&&a.colorImages&&a.colorImages[b]&&a.colorImages[b].length>
0&&a.colorImages[b][0]?a.colorImages[b][0].large:null,c=b)})});return m}})})})(function(){var g=window.AmazonUIPageJS||P,j=g.attributeErrors;return j?j("CommonDetailPageScripts"):g}());
;/* DetailPageCommonScripts */
(function(a){a.execute(function(){a.when("A","jQuery").register("jumpLink",function(a,c){return{bind:function(a,d,e){try{d=d||1E3,e=e||0,c("body").delegate(a,"click",function(b){try{var f=c(a);if(f.get(0)){var g=f.attr("href");g.charAt(0)==="#"&&(b.preventDefault(),c("html, body").animate({scrollTop:c(g).offset().top-e},d))}}catch(h){window.ueLogError&&window.ueLogError(h,{logLevel:"FATAL",attribution:"jumpLink",message:"[JumpLink - Error in executing click handler]"})}})}catch(b){window.ueLogError&&
window.ueLogError(b,{logLevel:"FATAL",attribution:"jumpLink",message:"[JumpLink - Error in binding click handler]"})}}}})})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("DetailPageCommonScripts"):a}());
;/* ProductBundleUIAssets */
(function(f){f.execute(function(){f.when("A","jQuery","a-carousel-framework","a-carousel-ajax-standard","ready").execute("bundle-discoverability-widget",function(c,d,j,k){function l(a,h,e){e._=c.now();a.triggerEvent("beforeAjax",{url:h,params:e});c.get(h,{success:function(b){(!b||!b.length)&&f.error("Carousel requires a set_size and none was returned by the fallback AJAX request","a-carousel-ajax-standard","sendRequest");var c=b[0].setSize?b[0].setSize:b.length;a.setAttr(m,c);for(var g=a.getAttr(i),
d;(d=b.pop())!==void 0&&e.offset+b.length<c;)g[e.offset+b.length]=d;if(g.length===c)for(b=c;b<n;++b)g[b]||(g[b]="&nbsp;");e.needSetSize&&a.init();a.setAttr(i,g);a.setAttr(o,!1);a.getAttr(p)>=g.length&&a.strategies.ajax.wantCurrentPage(a);a.triggerEvent("ajaxSuccess",{url:h,params:e})},params:e})}var i="fetchedItems",p="pageSize",m="set_size",o="ajaxLock",n=15,d=c.extend({},k);d.getItems=function(a,d,e){var b=a.getAttr("ajax");a.setAttr("requestTimer",c.delay(l,b.fetch_delay,a,d,e))};d.afterInit=function(a){a.strategies.ajax.wantCurrentPage(a);
a.onChange("pageNumber",function(d,e){var b=a.getAttr("ajax");d>e?(a.strategies.ajax.wantNextPage(a),c.get(b.nextPageReftagUrl,{})):(a.strategies.ajax.wantPrevPage(a),c.get(b.prevPageReftagUrl,{}))})};j.registerStrategy("ajax","bundle-discoverability",d)})})})(function(){var f=window.AmazonUIPageJS||P,c=f.attributeErrors;return c?c("ProductBundleUIAssets"):f}());
;/* RegistryDPAssets */
(function(m){m.execute(function(){m.when("A","a-popover","cf").register("add-to-wish-list",function(c,h){var m,B,C;function u(){e("#wishListDropDown").removeClass("a-button-selected");e("#wishListMainButton").removeClass("a-button-selected")}function q(a){c.state("atwl",e.extend(c.state("atwl")||{},a))}function v(){return(c.state("atwl")||{}).dropDownHtml}function Q(){q({dropDownHtml:""})}function D(){var a=e("#atwl-dd-ul").parent();if(a&&a.get(0)){var b=a.get(0).scrollHeight,d=a.height(),a=2*parseInt(a.css("padding-top"),
10);return b>d+a}return!1}function E(){return parseInt(e.browser.version,10)<9&&document.body&&document.body.parentElement?!(!document.body.parentElement.scrollLeft&&!document.body.parentElement.scrollTop):!1}function F(a){a.find(".a-button-close").hide();a.find(".a-popover-content").css({"margin-right":"0px"});a.css({padding:"0"});a.find(".a-popover-inner").css({padding:"0"});setTimeout(function(){a.removeClass("a-arrow-bottom");e("#atwl-rich-content").css({"margin-bottom":"0px",width:"auto"});if(e.browser.msie){var b=
c.state("atwl")||{},d=e("#"+b.wishlistButtonSubmitId),b=d.offset(),R=d.height(),d=b.left,b=b.top+R;E()&&(d+=document.body.parentElement.scrollLeft,b+=document.body.parentElement.scrollTop);D()&&(d-=17);a.css({left:d+"px",top:b+"px"})}},50)}function o(){if(r){var a=h.get(r);a&&a.hide()}}function w(a){e("#"+a).children().first().width(m);o();if(h){var b=h.get(r),d=c.state("atwl")||{},b=b?h.get(r):h.create(e("#add-to-wishlist-button-group"),{content:e("#"+a).html(),name:"atwl",skin:function(a){return a},
activate:"onmouseclick",width:m,position:d.dropDownPosition||"triggerBottom"});b.update({width:m,content:e("#"+a).html()});r=b.id;b.show().updatePosition();F(b.$popover)}}function x(){u();G++;o();w("atwl-dd-error-holder")}function S(){o();var a=c.state("atwl")||{};return G>=a.maxAjaxFailureCount}function H(){var a=c.state("atwl")||{};return h.create(e("#add-to-wishlist-button-group"),{content:v(),name:"atwl",skin:function(a){return a},activate:"onmouseclick",position:a.dropDownPosition||"triggerBottom"})}
function T(a){var b;b=E()?50:0;setTimeout(function(){var b=e("#atwl-popover-inner"),c=b.width();D()?c+=B:e(".atwl-dd-list-name").each(function(){var a=e(this);a.width(a.width()+C)});var f=a.find("ul li a.a-active").first();f.css("margin-left","1px");f.parent().focus();b.width(c)},b)}function U(a){a.update({content:v(),width:"auto"});a.show();F(a.$popover);T(a.$popover)}function I(){var a=h.get("atwl");if(a)if(a.isActive()){a.hide();return}else h.remove(a);else a=H(),h.remove(a);a=H();U(a);c.capabilities.touch&&
setTimeout(function(){var a=e("#wishlistButtonStack"),d=a.clone(),c=a.parent();a.remove();c.append(d)},300)}function s(){var a=h.get("atwl");a&&a.isActive()&&a.hide()}function V(a){u();o();var b;try{b=c.parseJSON(a)}catch(d){x();return}typeof b.html!=="undefined"&&b.css!=="undefined"?(q({dropDownHtml:b.html}),a=b.css,e("body").append(a),I()):x()}function W(a){if(a&&a.promoEnabled){var b=a.html;if(b){var d=h.create(y.parent(),{name:"kbpPromoPopover",content:b,position:"triggerBottom",width:a.width});
d.show().lock();c.delay(function(){var a=(c.state("atwl")||{}).kbpPromo||{};a.mouseOver?a.countDown=!0:(d.unlock().hide(),h.remove(d));c.state("atwl",{kbpPromo:a})},1E4)}}}typeof c.state.parse!=="undefined"&&c.state.parse();var j=c.state("popoverState")||{},z="#"+(j.formId||"addToCart");window.setRegistryId=function(a){var b=e(z);b.find("[name='sourceCustomerOrgListID'],[name='colid'],[name='wlPopCommand']").attr("value",a);b.find("[name='submit.add-to-registry.wishlist'],[name='submit.add-to-wishlist']").eq(0).click();
return!1};var t=[];if(j.showWishListDropDown||j.showBabyRegDropdown||j.isAddToWishListDropDownAuiEnabled||j.showPopover){var e=c.$;if(j.showWishListDropDown||j.showBabyRegDropdown){var p,J=function(){var a=function(a){if(!a.data("wired")){a.data("wired",!0);a[0].name="";if(a.css("cursor")!=="not-allowed"){var b=a.attr("data-type"),d=j.wishlistPopoverWidth;a.amazonPopoverTrigger({ajaxSlideDuration:0,align:"left",cacheable:!0,closeEventInclude:"CLICK_OUTSIDE",destination:"/gp/registry/reglist-popover.html?sprited=0&type="+
b,group:"addToWishlist",loadingContent:"<div style='padding: 4px 28px;'><img src='"+window.AmazonPopoverImages.loadingBar+"'/></div>",location:"bottom",locationElement:"#"+a[0].id,locationOffset:[0,-5],showOnHover:!1,skin:"<div id='wishlist-dropdown-content'><div class='ap_content'></div></div>",width:d,onFilled:function(a){e(document).click();a.width(d);window.wlPop&&setTimeout(function(){window.wlPop.onFill(a);a.width(d)},0)}})}p&&(clearInterval(p),p=void 0)}},b="#"+j.babyRegistryId;if(!j.isAddToWishListDropDownAuiEnabled){var d=
c.state("atwl")||{};b+=", #"+d.wishlistButtonId}e(b).each(function(){a(e(this))})};J();var n=function(){p&&clearInterval(p);p=setInterval(J,200)};e("#twister").change(n);c.declarative("swatchthumb-action","click",n)}if(j.isAddToWishListDropDownAuiEnabled){var r,G=0,n=c.state("atwl")||{},K=n.wireDeclaratives,L=e("#"+n.wishlistButtonId);L.addClass("a-declarative");L.attr("data-action","atwl-splitbutton-arrow");var y=e("#"+n.wishlistButtonSubmitId);y.addClass("a-declarative");y.attr("data-action","atwl-splitbutton-main");
e("#wishListMainButton").addClass("a-declarative").attr("data-action","add-wishlist-declarative");m=230;B=10;C=10;q({resetDropDownHtml:Q});K||(c.declarative("atwl-splitbutton-arrow","click",function(a){a.$event.preventDefault();setTimeout(function(){u()},0);if(a.$target.css("cursor")==="not-allowed")return!1;if(S())return o(),o(),w("atwl-dd-unavail-holder"),!1;var b=v(),a=c.state("atwl")||{};if(!b||!b.length){w("atwl-dd-spinner-holder");var b=c.state("wishlistDPState")||{},d="website.wishlist.detail.add";
if(typeof b.vendorId!=="undefined")d=b.vendorId;a={url:"/gp/registry/atwl/popover.html?"+e.param({sortMethod:a.sortMethod||0,type:"wishlist",useAll:a.showAllTypes||0,sourceVendorId:d}),cache:!1,success:V,error:x};e.ajax(a)}else I();return!1}),c.declarative("atwl-dd","click",function(a){a.$event.preventDefault();var b=a.data,a=b.id,b=b.type;typeof b==="undefined"&&(b="wishlist");var d="pop_"+a+"_"+b,c=e(z+",#addToWL");c.find("[name='sourceCustomerOrgListID'],[name='colid'],[name='wlPopCommand']").attr("value",
d);c.find("[name='registryID']").attr("value",a);c.find("[name='registryType']").attr("value",b);q({inSubmit:!0});c.find("[name='submit.add-to-registry.wishlist'],[name='submit.add-to-wishlist']").eq(0).click();s();return!1}),c.declarative("atwl-kbp-landing","click",function(a){var b=a.data,a=e(z).find("#ASIN").val(),b=b.url;b+="&asin="+a;window.open(b);return!1}));if((n=c.state("atwl")||{})&&n.sortMethod==="kbp")c.state("atwl",{kbpPromo:{mouseOver:!1,countDown:!1}}),c.ajax("/gp/toys/birthday/atwl-dpx.html",
{method:"get",cache:!1,params:{isAUI:1},success:W,error:function(){}}),K||(c.declarative("atwl-kbp-promo-mouseover","mouseleave",function(){var a=(c.state("atwl")||{}).kbpPromo;a.mouseOver=!1;if(a.countDown){var b=h.get("kbpPromoPopover");b&&(b.unlock().hide(),h.remove(b))}c.state("atwl",{kbpPromo:a})}),c.declarative("atwl-kbp-promo-mouseover","mouseenter",function(){var a=(c.state("atwl")||{}).kbpPromo;a.mouseOver=!0;c.state("atwl",{kbpPromo:a})}),c.on("a:popover:hide:kbpPromoPopover",function(){var a=
h.get("kbpPromoPopover");a.unlock().hide();h.remove(a)}));q({wireDeclaratives:!0})}if(j.showPopover){var M=function(a,b){var d=document.getElementById(j.formId||"addToCart");if(typeof d==="undefined"||d===null)d=document.getElementById("addToWL");var e=[];if(typeof d!=="undefined"&&d!==null){var e=[],f=!1,i=d.elements;i||(i=d.querySelectorAll("input"),f=!0);for(var l=0;l<i.length;l++){var g;if(!(g=f)){g=i[l];var h=/^(?:checkbox|radio)$/i,m=/^(?:submit|button|image|reset|file)$/i,n=/^(?:input|select|textarea|keygen)/i;
if(g){var o=g.type;g=g.name&&!g.disabled&&n.test(g.nodeName)&&!m.test(o)&&(g.checked||!h.test(o))}else g=!1}g&&e.push(i[l])}}f={};i=c.state("wishlistDPState")||{};if(typeof i.asin!=="undefined"&&i.asin!==null)f.asin=i.asin;for(l=0;l<e.length;l++)if(e[l].type!=="submit")f[e[l].name]=e[l].value;f.requestedQty=f.quantity=d!==null&&typeof d.quantity!=="undefined"?d.quantity.value:1;f.sid=typeof f["session-id"]!=="undefined"?f["session-id"]:i.sid;f.cache=!1;f.url=i[a+"Url"];f.action=a;f.type=f.registryType||
"wishlist";if(a==="add")f.type=f.registryType||b,f.caller="aui",f.streaming=i.streaming,f.sourceVendorId=typeof i.vendorId!=="undefined"?i.vendorId:"website.wishlist.detail.add";else if(a==="create")f.create_sid=f.sid,f.create_type=f.registryType||b,f.create_nextAction="add",f.create_includeEmptyList=1,f.create_isFirst=i.isFirstCreate?1:0,f.caller="aui",f.create_sourceVendorId=typeof i.vendorId!=="undefined"?i.vendorId:"website.wishlist.detail.add";return f},A=function(a){var b=a.attr("name"),a=a.parents("form"),
b=e('<input type="hidden" />').attr("name",b).val("1");a.append(e(b));a.submit()},N=function(){var a=e("#add-wishlist-declarative").closest(".a-button").find("input");A(a)};c.capabilities.touch||e("#add-to-wishlist-button-submit").unbind("click").bind("click",function(a){a.preventDefault();if(e(this).css("cursor")==="not-allowed")return!1;var b="",b=c.state("wishlistDPState")||{},d=e("[name='wlPopCommand']").val(),a=window.currentType;if(d&&d!==""){d=d.split("_");a=d[2];if(a!=="wishlist"&&a!=="giftlist"&&
a!=="supplylist"||e("html").hasClass("a-lt-ie9")){N();return}b=d[1]==="new"?"create":d[1]==="default"&&b.isFirstCreate?"create":"add"}else if(a="wishlist",b=b.isFirstCreate?"create":"add",b==="add"&&e("html").hasClass("a-lt-ie9")){N();return}c.state("wishlistDPState",{action:b,type:a});window.currentType=a;e("#add-wishlist-declarative").trigger("click")});var O=function(){for(var a=["wlPopCommand","sourceCustomerOrgListID"],b=0;b<a.length;b++){var c=e('[name^="'+a[b]+'"]');c&&c.length&&c.val("")}};
(c.state("wishlistDPState")||{}).eventsBound||(c.on("a:popover:show:addCreateToWishlist",function(a){var b=a.popover,a=b.$popover,d=c.state("wishlistDPState")||{},h=d.action;a.addClass("pop-huc-"+h);var f=b.$trigger.closest(".a-button").find("input"),a=d.type;f.closest(".a-button-selected").removeClass("a-button-selected");var a=M(h,a),d=a.url,i=a.streaming,l="ajax_"+i,g=new Date;window.ue&&window.uet("tc",l);var j=function(){b.hide();A(f)},m=function(){b.$popover.find("#popover-spinner").addClass("a-hidden");
O()},n=function(){window.ue&&(window.uet("be",l),window.uex("ld",l))},o=function(a,b,c){window.ue&&(window.ues("id",l,a),window.ues("t0",l,b),window.ues("ctb",l,c))};if(h==="create"||!i)c.ajax(d,{method:"post",params:a,success:function(a){a&&a.html?(o(a.requestId,g,"1"),a.status&&a.status==="no-asins"?j():(m(),h==="add"?b.$popover.find("#WLHUC_result").html(a.html).removeClass("a-hidden"):(b.$popover.find("#WLNEW_main").html(a.html).removeClass("a-hidden"),(a=c.state("atwl")||{})&&a.resetDropDownHtml&&
a.resetDropDownHtml()),b.updatePosition()),n()):(h==="create"&&A(f),b.hide())},error:j});else{var k=new XMLHttpRequest;k.open("GET",a.url+"&"+c.$.param(a),!0);k.send(null);var p=0;k.ontimeout=j;k.onerror=j;k.onreadystatechange=function(){try{if(k.readyState>2&&typeof k.status!=="unknown"&&k.status===200&&(typeof k.response!=="undefined"||typeof k.responseText!=="unknown"&&typeof k.responseText!=="undefined")){var a=[];typeof k.response!=="undefined"&&k.response!==null?a=k.response.split(",,,"):typeof k.responseText!==
"unknown"&&typeof k.responseText!=="undefined"&&k.responseText!==null&&(a=k.responseText.split(",,,"));for(var d=p;d<a.length;d++){var f=a[d],g;try{g=c.parseJSON(f)}catch(h){p=d;break}d===0&&g&&g.name==="skeleton"?g&&g.html&&(o(g.requestId,new Date,"1"),g.status&&g.status==="no-asins"?j():(m(),b.$popover.find("#WLHUC_result").html(g.html).removeClass("a-hidden"))):g&&g.name&&g.html&&g.name==="pcomp"?e("#wishListMainButton").hasClass("a-hidden")||(e("#wishListMainButton,#add-to-wishlist-button-group").addClass("a-hidden"),
s(),e("#wishlistButtonStack").append(g.html)):g&&g.name&&g.html&&g.name!=="js"?(b.$popover.find("#"+g.name).html(g.html),d===1&&window.ue&&window.uet("cf",l)):g&&g.html&&b.$popover.find("#WLHUC_result").append(g.html);b.updatePosition()}k.readyState===4&&n()}else typeof k.status!=="unknown"&&k.status!==200&&j()}catch(i){j()}}}}),c.on("a:popover:beforeShow:addCreateToWishlist",function(a){var a=a.popover,b=c.state("wishlistDPState")||{};a.$popover.find("#popover-spinner").css({margin:"10% 40%"});a.$popover.find("#popover-spinner").removeClass("a-hidden");
a.$popover.find(".wlAddCreatePop").html("").addClass("a-hidden");var d=b.action;a.update({width:b[d+"Width"],header:b[d+"Header"],height:b[d+"Height"]});a.updatePosition()}),c.on("a:popover:hide:addCreateToWishlist",function(){e(".a-modal-scroller").css({visibility:"hidden"});O()}),c.state("wishlistDPState",{eventsBound:!0}),c.declarative("add-wishlist-declarative",["click"],function(){var a=c.state("wishlistDPState")||{},b=M(a.action,a.type),d=function(){e("#wishListMainButton,#add-to-wishlist-button-group").addClass("a-hidden");
s();e("#atwl-error-holder").removeClass("a-hidden")};e("#atwl-dd-no-title-holder").hasClass("a-hidden")||e("#atwl-dd-no-title-holder").addClass("a-hidden");var h=function(a){try{if(typeof a!=="undefined"){var b="";if(typeof a.pcompHtml!=="undefined"&&a.pcompHtml.trim()!=="")b=a.pcompHtml;else{d();return}e("#wishListMainButton").hasClass("a-hidden")||(e("#wishListMainButton,#add-to-wishlist-button-group").addClass("a-hidden"),s(),e("#atwl-output-holder").empty(),e("#atwl-output-holder").append(b),
e("#atwl-output-holder").removeClass("a-hidden"))}else d();for(b=0;b<t.length;b++)if(typeof t[b]==="function")t[b](a)}catch(c){d()}},f=function(a){var b=document.createElement("input");b.type="hidden";b.id=a;b.name=a;typeof e("#addItemForm")!=="undefined"&&e("#addItemForm").append(b);return b};if((typeof b.asin==="undefined"||b.asin.length===0)&&(typeof b.name==="undefined"||b.name.length===0))e("#atwl-dd-no-title-holder").removeClass("a-hidden");else if(a.custRecognized==="false"){if(a.asin===null){var a=
f("name.0"),b=f("imageUrl.0"),h=f("productUrl.0"),i=f("priceInput"),f=f("quantity.0");a.value=document.getElementById("name").value;b.value=document.getElementById("imageUrl").value;h.value=document.getElementById("productUrl").value;i.value=document.getElementById("price").value;f.value=1}e("#addItemForm").submit()}else c.ajax(b.url,{method:"get",dataType:"json",cache:!1,params:b,success:h,error:d})}))}}return{setPostAddSuccess:function(a){t.push(a)}}})})})(function(){var m=window.AmazonUIPageJS||
P,c=m.attributeErrors;return c?c("RegistryDPAssets"):m}());
;/* SoftlinesRecommendationsAssets */
(function(b){b.execute(function(){b.when("A","jQuery","a-carousel-framework","a-carousel-ajax-standard","complete-the-look-carousel-data","looks-data-cache","softlines-utils","csm-metrics-logger","ob-link-generator","lookFeedback","ready").execute("complete-the-look-ajax",function(a,j,b,c,m,g,l,i,k,e){a=a.extend({},c);a.getItems=function(a,j,e){e.asin=g.getAsin();var b=g.getInjectedViewModel();if(l.isStringNotEmpty(b))e.injectViewModel=b;c.getItems(a,j,e)};a.init=function(a){e.updateFeedback(1);var j=
m.getProducts();a.setAttr("ajax",{url:"/gp/product/ajax-handlers/complete-the-look-carousel.html",id_list:j});return c.init(a)};a.afterInit=function(a){c.afterInit(a);var b=g.getLooks(),h=0;if(j.isArray(b))h=b.length;i.addCount("ctl-carousel:shown",1);a.onChange("pageNumber",function(a,c){var p=":back";a>c&&(p=":next");a===h&&c===1&&(p=":back");c===h&&a===1&&(p=":next");e.updateFeedback(a);var b=j("#outfitBuilder");if(b.length>0){var d=k.getOutfitBuilderUrlForPageNumber(a);l.isStringNotEmpty(d)&&
b.attr("href",d)}i.addCount("ctl-carousel:page:"+a+p,1)})};b.registerStrategy("ajax","complete-the-look",a)});b.when("A","jQuery","a-carousel-framework","looks-data-cache","complete-the-look-carousel-data","csm-metrics-logger","ready").execute("complete-the-look-display",function(a,b,n,c,m,g){function l(a){function c(a){a.dom.$viewport.css("height","")}a.onChange(h,function(){a.dom.$carousel.children("li").css("visibility","")});a.onChange(k,function(b,d){b>d&&c(a)});a.onChange("loading",function(b){b||
c(a)});a.onChange(e,function(){c(a)});a.onChange(o,function(c){if(!c){var d=a.getAttr(e)-1,f=d+a.getAttr(k);a.dom.$carousel.children("li").each(function(a,c){var e=a>=d&&a<f;b(c).css("visibility",e?"":"hidden").attr("aria-hidden",e?"false":"true")})}});a.onChange(d+" "+f,function(){this.repaint(a)});a.onChange(f,function(){this.repaint(a)})}var i=0.82,k="pageSize",e="firstVisibleItem",d="single_page_align",f="minimum_gutter_width",h="pageNumber",o="animating",q=b("#recommendations");n.registerStrategy("display",
"complete-the-look",{repaint:function(a){c.isAsinTypeCtl()||(i=1);a.getDimensions();var b=q.width()*i,d=Math.round(b*0.225),j=Math.round(b*0.0125);a.setAttr("currentGutter",0);a.setAttr(k,4);var f=a.dom.$carousel,g=f.children("li"),b=g.length,h=a.getAttr(e)-1,m=h+4,l=d+"px",o="0 "+j+"px";g.each(function(a,b){var c=a>=h&&a<m;b.style.visibility=c?"":"hidden";b.style.width=l;b.style.margin=o;b.setAttribute("aria-hidden",c?"false":"true")});j=g.first().outerWidth(!0);g=b*j;f.removeClass("a-text-right a-text-center");
f.css("width",g+"px");f={carousel:{width:g,outerWidth:f.outerWidth()},items:[]};for(g=0;g<b;g++)f.items.push({width:d,outerWidth:j});a.updateDimensionsCache(f);a.gotoIndex(a.getAttr(e),{animationDuration:0});a.triggerEvent("repaint")},resize:function(a,b){b.viewport&&b.viewport.width!==void 0&&(this.repaint(a),g.addCount("ctl-carousel:resized",1))},init:function(a){var b=m.getProducts();c.isAsinTypeCtl()||(b=[]);b.length>0&&a.setAttr("set_size",b.length);a.setAttr(f,0);a.setAttr("first_item_flush_left",
!0);this.repaint(a);b=a.getDimensions();a.dom.$container.find(".a-carousel-left, .a-carousel-right, .a-carousel-viewport").css("height",Math.max(b.viewport.height,b.items[0]?b.items[0].height:0)+"px");b=a.getAttr(e);b>1&&(a.setAttr(e,b),b=Math.ceil(b/a.getAttr(k)),a.gotoPage(b));l(a)}})});b.when("jQuery").register("softlines-utils",function(a){function b(c){return a.type(c)!=="undefined"&&a.type(c)!=="null"}function n(c){return b(c)&&a.type(c)==="string"}return{isNotNull:b,isString:n,isStringNotEmpty:function(a){return n(a)&&
a.length>0}}});b.register("recommendations-carousel-data",function(){return{getProducts:function(){}}});b.when("A","jQuery","recommendations-carousel-data","softlines-utils","looks-data-cache","atf").register("complete-the-look-carousel-data",function(a,b,n,c,m){a=a.extend({},n);a.getProducts=function(){var a=[],l=m.getLooks(),i,k,e=l.length;for(i=0;i<e;i++)if(k=l[i],b.isPlainObject(k)&&b.isArray(k.asins)){var d=k.asins,f=d.length;for(k=0;k<f;k++){var h=d[k];b.isPlainObject(h)&&c.isString(h.asin)&&
a.push(h.asin)}}return a};return a});b.when("A","jQuery","softlines-utils","atf").register("looks-data-cache",function(a,b,n){var c=b("#multipleRecommendations"),m=[],g=!1,l=[];if(c.length>0){var i=c.attr("data-ids");if(n.isString(i)&&(a=a.parseJSON(i),b.isPlainObject(a)&&b.isArray(a.recommendations)))for(var a=a.recommendations,k=a.length,i=0;i<k;i++){var e=a[i];if(b.isPlainObject(e)&&b.isArray(e.asins)){var d=e.asins;if(b.isArray(d)){d=d.splice(0,Math.min(4,d.length));e.asins=d;l.push(e);for(var f=
d.length,h=[],e=0;e<f;e++){var o=d[e];b.isPlainObject(o)&&n.isString(o.asin)&&(h.push(o.asin),o.asinDataSetType==="SOFTLINES_CTL"&&(g=!0))}d=h.join();d=encodeURIComponent(d);m.push(d)}}}}var o=c.attr("data-asin"),q=c.attr("data-injectedViewModel");return{getLooks:function(){return l},getLooksAsins:function(){return m},getAsin:function(){return o},isAsinTypeCtl:function(){return g},getInjectedViewModel:function(){return q}}});b.when("A","metrics-logger").register("csm-metrics-logger",function(a,b){var n=
window.ue,c=a.extend({},b);c.addCount=function(a,b){var c=n.count(a)||0;n.count(a,c+b)};return c});b.register("metrics-logger",function(){return{addCount:function(){}}});b.when("jQuery","softlines-utils","looks-data-cache").register("ob-link-generator",function(a,b,n){return{getOutfitBuilderUrlForPageNumber:function(c){c-=1;var m,g=a("#outfitBuilder"),l=n.getLooksAsins();c>=0&&c<l.length&&g.length>0&&(g=g.data("outfitbuilderurlprefix"),b.isStringNotEmpty(g)&&(m=g+l[c]));return m}}});b.when("jQuery",
"softlines-utils","looks-data-cache","atf").register("lookFeedback",function(a,b,n){function c(){h.length>0&&f.length>0&&(h.removeClass(),f.removeClass(),h.addClass("leftFloat"),f.addClass("leftFloat"),h.addClass("hidden"),f.addClass("visibleFeedbackBlock"));typeof Storage!=="undefined"&&localStorage.setItem(g,e)}function m(b){a.ajax({timeout:d,type:"GET",url:"/gp/softlines/logger/seed/"+i+"/look/"+l+("/ref=ctl_look_"+k+"_vote_"+b),data:{vote:b}})}var g,l,i=n.getAsin(),k,e="1",d=4E3,f=a("#afterCtlFeedback"),
h=a("#beforeCtlFeedback");a("#ctlButtonYes").click(function(){c();m("yes")});a("#ctlButtonNo").click(function(){c();m("no")});return{updateFeedback:function(a){k=a;a-=1;var b=n.getLooksAsins();a>=0&&a<b.length&&(l=b[a]);g=i+l;typeof Storage!=="undefined"&&(a=localStorage.getItem(g),h.length>0&&f.length>0&&(h.removeClass(),f.removeClass(),h.addClass("leftFloat"),f.addClass("leftFloat"),a===e?(h.addClass("hidden"),f.addClass("visibleFeedbackBlock")):(h.addClass("visibleFeedbackBlock"),f.addClass("hidden"))))}}})})})(function(){var b=
window.AmazonUIPageJS||P,a=b.attributeErrors;return a?a("SoftlinesRecommendationsAssets"):b}());
;/* FreeSampleAssets */
(function(e){e.execute(function(){e.when("A","ready").execute(function(a){a.$("#freeSampleInlineJavascript").length===0&&e.register("sampling-feature",function(){var c,e,j,n,m,f;function b(){var b=a.$("#csxfsSelectedBlock").height()*n;a.$("#csxfsImageSelected").css("padding-top",b);a.$("#csxfsYourGiftText").css({left:m,opacity:0});a.$("#csxfsSampleImages").css({height:0,opacity:0});a.$(".csxfs_normal").each(function(){a.$(this).css("borderWidth",f)})}m=16;f=0;j=114;c=void 0;e=void 0;n=void 0;var h,
k=function(){a.$("#csffsFeaturecontainer").animate({height:c},"slow",function(){a.$("#csxfsSelectedSampleText").css({left:m,opacity:0})});a.$("#csxfsSamplesBlock").removeClass("a-hidden");a.$("#csxfsSelectedBlock").addClass("a-hidden");a.$("#csxfsImageSelected").removeClass("csxfs_faded_image");a.$("#csxfsSampleImages").animate({height:e,opacity:1},"slow");a.$(".csxfs_normal").each(function(){a.$(this).animate({borderWidth:1},"3000")});a.$("#csxfsYourGiftText").animate({left:0,opacity:1},"slow");
d(!0);return!1},d=function(b){b?(a.$("#csxfsFreeSampleDeclinedTitle").hide(),a.$("#csxfsSelectedSampleText").removeClass("csxfs_nosampleselected_text"),a.$("#csxfsSampleTitle").show(),a.$("#csxfsFreeSampleTitle").show()):(a.$("#csxfsFreeSampleDeclinedTitle").show(),a.$("#csxfsSelectedSampleText").addClass("csxfs_nosampleselected_text"),a.$("#csxfsSampleTitle").hide(),a.$("#csxfsFreeSampleTitle").hide())},q=function(){h=!1;a.$("#csxfsLnkDiffGiftSec").hide();a.$("#csxfsLnkChooseGift").show();a.$("#csxfsLnkNoGift").hide();
d(!1);a.$("#csxfsImageSelected").addClass("csxfs_faded_image");a.$("#freeSampleOfferListingID").remove();a.$("#csxfsAcceptSample").show();a.$.get(a.$(this).data("foresterurl"));return!1},l=function(){return a.$("#csxfsItemsCount").val()>1?!0:!1},i=function(){var b=a.$(this).data("foresterurl");b&&a.$.get(b);l()?u():(r(),a.$("#addToCart").find("#freeSampleOfferListingID").val(a.$("#csxfsImg0").data("offerlistingid")),a.$("#csxfsSampleTitle").text(a.$("#csxfsImg0").data("title")).show(),a.$("#csxfsImageSelected").removeClass("csxfs_faded_image"),
a.$("#csxfsLnkNoGift").show(),d(!0),a.$("#csxfsAcceptSample").hide())},u=function(){a.$("#csxfsLnkDiffGiftSec").show();a.$("#csxfsLnkChooseGift").hide();a.$("#csxfsLnkNoGift").show();k();return!1},r=function(){h||(a.$("#addToCart").prepend(a.$('<input type="hidden" id="freeSampleOfferListingID" name="freeSampleOfferListingID" value="">')),h=!0)},s=function(){var c=a.$(this).find("img").attr("src"),d=a.$(this).data("title");a.$("#csxfsSampleImages").animate({height:0,opacity:0},"slow");a.$("#csxfsSamplesBlock").addClass("a-hidden");
a.$("#csxfsImageSelected").attr("src",c);a.$("#csxfsSampleTitle").text(d);a.$("#csxfsSelectedBlock").removeClass("a-hidden");c=a.$("#csxfsSelectedBlock").height()*n;a.$("#csxfsImageSelected").css("padding-top",c);a.$("#csffsFeaturecontainer").animate({height:j},"3000",function(){a.$("#csxfsYourGiftText").css({left:m,opacity:0})});a.$("#csxfsSelectedSampleText").animate({left:0,opacity:1},"slow");a.$(".csxfs_normal").each(function(){a.$(this).removeClass("csxfs_highlight")});a.$(this).addClass("csxfs_highlight");
b();r();a.$("#addToCart").find("#freeSampleOfferListingID").val(a.$(this).data("offerlistingid"));a.$.get(a.$(this).data("foresterurl"))},g,o=!0,p=function(){o=!0;a.$("#csxfsSampleTitle").removeClass("csxfs_hidden_elements");a.$("#csxfsNoSample").addClass("csxfs_hidden_elements");a.$("#csxfsImageSelected").removeClass("csxfs_faded_image");if(l()){var b=a.$("#csxfsSampleTitle").text().trim(),c=a.$(this).data("title"),b=b.substring(0,b.indexOf(" ")+1)+c;a.$("#csxfsSampleTitle").text(b);a.$("#csxfsSelectProductSubheadingText").text(c);
g=c;c=a.$(this).find("img").attr("src");a.$("#csxfsImageSelected").attr("src",c);a.$(".csxfs_normal").removeClass("csxfs_highlight");a.$(this).addClass("csxfs_highlight");a.$("#csxfsButtonTextChange").removeClass("csxfs_hidden_elements");a.$("#csxfsButtonTextSelect").addClass("csxfs_hidden_elements");a.$("#csxfsFreeSampleTitle").removeClass("csxfs_hidden_elements");a.$("#csxfsTitleDetailsLink").removeClass("csxfs_hidden_elements");a.$("#csxfsSelectSampleTitle").addClass("csxfs_hidden_elements");a.$("#csxfsCountSampleChoices").addClass("csxfs_hidden_elements");
a.$("#freeSampleOfferListingID").val(a.$(this).data("offerlistingid"));a.$.get(a.$(this).data("foresterurl"))}else a.$("#csxfsDeclineSampleButton").removeClass("csxfs_hidden_elements"),a.$("#csxfsAcceptSampleButton").addClass("csxfs_hidden_elements"),a.$("#freeSampleOfferListingID").val(a.$("#csxfsImg0").data("offerlistingid")),a.$.get(a.$("#csxfsImg0").data("foresterurl"))},t=function(){o=!1;a.$("#csxfsSampleTitle").addClass("csxfs_hidden_elements");a.$("#csxfsNoSample").removeClass("csxfs_hidden_elements");
a.$("#csxfsImageSelected").addClass("csxfs_faded_image");if(l()){a.$(".csxfs_normal").removeClass("csxfs_highlight");a.$("#csxfsNoThanks").addClass("csxfs_highlight");var b=a.$(this).data("title");a.$("#csxfsSelectProductSubheadingText").text(b);g=b;a.$("#csxfsButtonTextChange").addClass("csxfs_hidden_elements");a.$("#csxfsButtonTextSelect").removeClass("csxfs_hidden_elements");a.$("#csxfsFreeSampleTitle").addClass("csxfs_hidden_elements");a.$("#csxfsTitleDetailsLink").addClass("csxfs_hidden_elements");
a.$("#csxfsSelectSampleTitle").removeClass("csxfs_hidden_elements");a.$("#csxfsCountSampleChoices").removeClass("csxfs_hidden_elements")}else a.$("#csxfsDeclineSampleButton").addClass("csxfs_hidden_elements"),a.$("#csxfsAcceptSampleButton").removeClass("csxfs_hidden_elements");a.$("#freeSampleOfferListingID").val("");a.$.get(a.$("#csxfsNoThanks").data("foresterurl"));return!1},v=function(){o?t():p()},w=function(){g=a.$("#csxfsSelectProductSubheadingText").text();a.$("#csxfsSelectProductSubheadingText").text(a.$(this).data("title"))},
x=function(){a.$("#csxfsSelectProductSubheadingText").text(g)};return{init:function(){a.$(".csxfs_featurecontainer").show();var d=a.$("#csffsFeaturecontainer").hasClass("a-hidden");a.$("#csffsFeaturecontainer").removeClass("a-hidden");c=a.$("#csxfsSamplesBlock").removeClass("a-hidden").height();e=a.$("#csxfsSampleImages").height();a.$("#csxfsSamplesBlock").addClass("a-hidden");j=a.$("#csffsFeaturecontainer").height();d&&a.$("#csffsFeaturecontainer").addClass("a-hidden");a.$("#csxfsImageSelected").hasClass("csxfs_faded_image")&&
a.$("#addToCart").find("#freeSampleOfferListingID").val("");b();a.$("#csxfsLnkDiffGift").bind("click",k);a.$("#csxfsLnkNoGift").bind("click",q);a.$(".csxfs_normal").bind("click",s);a.$("#csxfsImageSelected").bind("click",i);a.$("#csxfsLnkChooseGift").bind("click",u);a.$("#csxfsAcceptSample").bind("click",i)},initV2:function(b,c){a.$(".csxfs_featurecontainer").show();h=!1;r();l()?(a.$("#csxfsSelectSampleButton, #csxfsImageSelected").bind("click",function(){b.animateIn(c)}),a.$(".csxfs_normal").bind("click",
p).bind("click",function(){b.animateOut(c)}),a.$(".csxfs_normal").hover(w,x),a.$("#csxfsNoThanks").bind("click",t).unbind("click",p)):(a.$("#csxfsImageSelected").bind("click",v),a.$("#csxfsAcceptSampleButton").bind("click",p),a.$("#csxfsDeclineSampleButton").bind("click",t));a.$("#csxfsImageSelected").hasClass("csxfs_faded_image")?(o=!1,a.$("#addToCart").find("#freeSampleOfferListingID").val("")):a.$("#freeSampleOfferListingID").val(a.$("#csxfsImg0").data("offerlistingid"))}}})})})})(function(){var e=
window.AmazonUIPageJS||P,a=e.attributeErrors;return a?a("FreeSampleAssets"):e}());
;/* BurjDesktopAssets */
(function(g){g.execute(function(){g.when("jQuery").register("action-panel",function(a){var b=["ap-onetime","ap-sns","ap-deal","ap-mom","ap-fresh"];return{setPanelState:function(c){if(c.mode){for(var d=a("#actionPanel"),e=0;e<b.length;e++)d.removeClass(b[e]);c="ap-"+c.mode;a.inArray(c,b)>=0&&d.addClass(c)}}}});g.when("jQuery","ready").register("action-panel-secondary-panel",function(a){function b(b,c){if(b&&c&&e[b])a("#"+b+"_secondaryPanelHeadingText").text(c),e[b].heading=c}function c(b,c){if(b&&
c&&e[b]){var d=a("#"+c);if(d.length>0)c!==e[b].contentId&&a("#"+e[b].contentId).addClass("aok-hidden"),a("#"+b+"_secondaryPanelContent").append(d),d.removeClass("aok-hidden"),e[b].contentId=c}}function d(b){b&&e[b]&&a("#actionPanel").animate({left:"+=420px"},400,"swing",function(){a("#"+b+"_secondaryPanel").addClass("aok-hidden");a("#"+b+"_secondaryPanelBackButton").removeClass("backButtonClickedState")})}var e={};return{init:function(f){if(f.panelId&&!e[f.panelId]){e[f.panelId]=f;f.heading&&b(f.panelId,
f.heading);f.contentId&&c(f.panelId,f.contentId);var h=a("#"+f.panelId+"_secondaryPanelBackButton");h.click(function(){h.addClass("backButtonClickedState");d(f.panelId)})}},setHeading:b,setContent:c,animateIn:function(b){b&&e[b]&&(a("#"+b+"_secondaryPanel").removeClass("aok-hidden"),a("#actionPanel").animate({left:"-=420px"},400,"swing"))},animateOut:d}});g.when("jQuery","action-panel").register("toggleBB",function(a,b){return{init:function(){a('input[name="toggleBuyBox"]:radio').change(function(){var c=
a(this).attr("value");b.setPanelState({mode:c});c==="onetime"?a("#csffsFeaturecontainer").removeClass("a-hidden"):a("#csffsFeaturecontainer").addClass("a-hidden")})}}});g.when("jQuery","ready").register("burj-featurebullets",function(a){var b=!1,c=!0,d,e,f=function(){e.fadeTo(200,0.75);c?(b=!0,d.find(".a-expander-container").removeClass("a-spacing-base"),d.find(".a-vertical").removeClass("collapsedFeatureBullets"),e.addClass("expandedFeatureBullets"),e.find(".a-size-medium").addClass("expandedFBHeader"),
a("#featureBulletsPlaceholder").addClass("FBplaceholder"),d.find(".a-expander-header").hide(),d.find(".a-expander-collapsed-height").removeAttr("style"),setTimeout(function(){a("#feature-bullets")[0].offsetHeight<a("#feature-bullets")[0].scrollHeight&&(a(".fadeTextTopforFB").show(),a(".fadeTextBottomforFB").show())},1),e.find(".closeFB").removeClass("aok-hidden")):setTimeout(function(){c=!c;e.find(".closeFB").addClass("aok-hidden");a("#featureBulletsPlaceholder").removeClass("FBplaceholder");d.find(".a-vertical").addClass("collapsedFeatureBullets");
e.removeClass("expandedFeatureBullets");e.find(".a-size-medium").removeClass("expandedFBHeader");a(".fadeTextTopforFB").hide();a(".fadeTextBottomforFB").hide();d.find(".a-expander-header").show()},10);e.fadeTo(200,1)},h=function(){b&&(b=!b,c=!1,d.find(".moreButtonforFB").trigger("click"))};return{init:function(){d=a("#feature-bullets");e=a("#fbSection");if(d.find(".a-expander-header").length){var b=a("#fbSection");d.find(".a-declarative").addClass("a-button a-button-toggle moreFB");d.find(".a-expander-prompt").addClass("moreButtonforFB");
d.find(".a-icon").hide();d.addClass("showAllFeatureBullets");a(".fadeTextTopforFB").hide();a(".fadeTextBottomforFB").hide();d.find(".a-expander-content").removeAttr("style");e.find(".downArrowInMoreButton").insertAfter("#feature-bullets .a-expander-prompt");e.find(".downArrowInMoreButton").removeClass("aok-hidden");d.removeClass("a-spacing-medium a-spacing-top-small");d.find(".moreFB").click(function(){f()});e.find(".closeFB").click(function(){h()});b.hover(null,h)}}}});g.when("jQuery","ready").register("elevatorFeature",
function(a){var b,c,d,e,f,h,p,j=function(){window.pageYOffset>e?(b.addClass("stickyBar"),d.removeClass("aok-hidden"),c.removeClass("aok-hidden")):(b.removeClass("stickyBar"),d.addClass("aok-hidden"),c.addClass("aok-hidden"))},k=function(){var b=window.pageYOffset,c,e;for(c=0,e=p.length;c<e;++c){var d=p[c],h=a(d.element);if(h.length>0){var m=h.offset().top-f-10,h=m+h.height(),g;b>=m-10&&b<=h+10?(a(d.selector).addClass("elevatorHighlight"),g=d.selector):a(d.selector).hasClass("elevatorHighlight")&&
g!==d.selector&&a(d.selector).removeClass("elevatorHighlight")}}},i=function(a){if(a.length>0){var b=a.offset().top-f-10;q(b,a)}},q=function(b,c){var d=a(window).scrollTop(),e=Math.abs(d-b)+0,m=e/2E3*1E3,g=d-b<0,j=!1,i=g?b-e*0.2:b+e*0.2;h=!0;a(".elevatorButton").removeClass("elevatorHighlight");a("html, body").animate({scrollTop:b},{duration:m<500?500:m,step:function(a,d){if(c&&!j&&(g?a>i:a<i)){j=!0;var e=c.offset().top-f-10;if(b!==e)d.end=e}},complete:function(){h=!1;k()}})},l=function(b,c,d){var e=
a(b);e.length?(p.push({selector:c,element:b}),a(c).click(function(){e=a(b);i(e)})):a(d).addClass("aok-hidden")},n=function(){var b=[];a("#beautyRecommendations").length&&b.push("#beautyRecommendations");a("#sims_fbt").length&&b.push("#sims_fbt");a("#session-sims-feature, #fallbacksession-sims-feature").length&&b.push("#session-sims-feature, #fallbacksession-sims-feature");a("#purchase-sims-feature").length&&b.push("#purchase-sims-feature");if(b.length)b.sort(function(b,c){return a(b).offset().top-
a(c).offset().top}),b.forEach(function(a){p.push({selector:"#elevatorRelatedProductsSection",element:a})}),a("#elevatorRelatedProductsSection").click(function(){for(var c=window.pageYOffset,d=0,e=b.length,h=null;h===null&&d<e;){var m=a(b[d++]);m.length>0&&Math.floor(m.offset().top-f-10)>c&&(h=m)}h===null&&d===e&&(h=a(b[0]));i(h)});else{a("#elevatorRelatedProductsSection").addClass("aok-hidden");for(var c=a(".elevatorDividerSection"),e=!0,d=c.length-1;e&&d>=0;){var h=a(c[d]);h.hasClass("aok-hidden")?
d--:(h.addClass("aok-hidden"),e=!1)}}},r=function(){a("#elevatorViewBuyingOptionsButton .a-button-inner").click(function(){q(a("#a-page .a-container").offset().top-10,null)})},o;g.when("page-refresh:page").execute(function(a){o=a});var s=function(){if(o&&o.config){var b=!1,c;for(c in o.config)if(o.config[c].affectedFeatures&&(a(o.config[c].affectedFeatures).each(function(c,d){var e=a(d);e.css("display")!=="none"&&e.css("opacity")!=="1"&&(b=!0)}),b))return!0}return!1},m=function(){if(s())setTimeout(function(){m()},
200);else{b=a("#elevatorBar");c=a("#elevatorBarPlaceholder");d=a("#elevatorViewBuyingOptionsSection");e=b.position().top;f=b.height();p=[];var g=!1;h=!1;l("#productDescription, #product-description_feature_div, #product-description-iframe","#elevatorMoreAboutThisItemSection","#elevatorMoreAboutThisItemSection, #elevatorMoreAboutThisItemDivider");l("#detail-bullets, #prodDetails","#elevatorProductDetailsSection","#elevatorProductDetailsSection, #elevatorProductDetailsDivider");l("#quickPromoBucketContent",
"#elevatorSpecialOffersSection","#elevatorSpecialOffersSection, #elevatorSpecialOffersDivider");l("#cm_cr_dpwidget","#elevatorCustomerReviewsSection","#elevatorCustomerReviewsSection, #elevatorCustomerReviewsDivider");n();r();a(window).resize(function(){e=b.position().top});a(window).scroll(function(){g=!0});setInterval(function(){g&&(g=!1,j(),h||k())},100);j();k()}};return{init:m}});g.when("jQuery","atf").register("title-burj",function(a){var b,c,d,e,f,h,p,j,k,i,q,l,n=function(){e.text(f);if(i&&
b.height()<c.height()){k.removeClass("aok-hidden");if(j){p=f;for(var a=0,g=f.length-1;a<g;){e.text(f);var t=f,v=a+Math.floor((g-a)/2),l=t.indexOf(" ",v),t=t.substring(0,l!==-1?l:t.length-1);e.text(t+"...");b.height()<c.height()?g=v-1:(a=v+1,p=e.text())}j=!1}e.text(p);d.addClass("showPointerOnHover");h=!0}else i&&(k.addClass("aok-hidden"),d.removeClass("showPointerOnHover"),h=!1)},r=function(){h&&c.fadeTo(200,0.75,function(){i?(l(),k.removeClass("expand").addClass("collapse titleToggleClickedState"),
b.addClass("expandedTitle")):(q(),k.removeClass("collapse").addClass("expand titleToggleClickedState"),b.removeClass("expandedTitle"));i=!i;n();a("#titleOverlay").height(c.height()+16);c.fadeTo(200,1,function(){k.removeClass("titleToggleClickedState")})})},o=function(){i||r()},s=function(){j=!0;n()};return{init:function(){b=a("#title_feature_div");c=a("#titleSection");d=a("#title");e=a("#productTitle");f=e.text();h=!1;i=!0;k=a("#expandTitleToggle");g.when("A","a-tooltip","atf").execute(function(a,
b){q=function(){b.create(k,{content:a.state("titleExpanderTooltipState").content,position:"triggerTop"})};l=function(){b.remove(k)};i&&q()});a("#socialFabric").append(a('<hr class="a-spacing-medium a-divider-normal">'));s();a(window).resize(s);d.click(r);k.click(r);c.hover(null,o)}}});g.when("A","jQuery","a-popover","cf").register("actionpanel-modified-popover",function(a,b,c){return function(d,e){function f(){n=b("#"+j);if(!n.length){var a=document.createElement("div"),c=b(q);if(c.length)a.id=j,
n=b(a).addClass(k).css({width:c.outerWidth(),height:b(l).outerHeight(),top:c.position().top}).bind("touchend click",function(){return!1}),b(q).append(a)}}function h(a){n.show();a.popover.$container.css("top",a.popover.$trigger.offset().top);a.popover.$container.hasClass(i)||a.popover.$container.addClass(i);a.popover.$trigger.trigger(o,a)}function g(a){n.hide();a.popover.$trigger.trigger(s,a)}var j="actionPanelOverlay",k="action-panel-overlay",i="burj-action-panel-modified-popover",q="#actionPanel",
l="#leftCol",n,r=this,o="ActionPanelModifiedPopover.showPopover",s="ActionPanelModifiedPopover.hidePopover";(function(d,e){var j=b(e);r.popoverHandle=c.create(j,{closeButton:!1,position:"triggerBottom",name:d,activate:"onclick",width:"400"});a.on("a:popover:afterShow:"+d,h);a.on("a:popover:afterHide:"+d,g);f()})(d,e)}});g.when("A","ready").execute(function(a){var b=function(){return a.$("#couponFeature").hasClass("vpc_signedIn")},c=function(){return a.$("#couponFeature").hasClass("vpc_clipped")},
d=function(){a.$("#couponFeature").addClass("vpc_clip_error");a.$("#couponFeature").removeClass("vpc_clipped");a.$("#couponFeature").removeClass("vpc_unclipped")};window.displayClipCouponResult=function(b){c()||(b.indexOf("SUCCESS")>-1||b.indexOf("REDEEMED")>-1?(a.$("#couponFeature").removeClass("vpc_unclipped"),a.$("#couponFeature").addClass("vpc_clipped")):d(),typeof window.displaySpecialOffersClipCouponResult==="function"&&window.displaySpecialOffersClipCouponResult(b))};var e=function(){d()},
f=function(c){b()?a.$.ajax({type:"GET",url:"/gp/promotions/vpc?ie=UTF8&promoId="+a.$("#couponFeature").attr("data-vpcpromoid")+"&source=dp_"+a.$("#couponFeature").attr("data-vpcasin"),success:window.displayClipCouponResult,error:e}):window.location="/gp/sign-in.html/ref=sr_1_1?ie=UTF8&email=&redirectASIN="+a.$("#couponFeature").attr("data-vpcasin")+"&disableCorpSignUp=&path=%2Fgp%2Fcoupon%2Fc%2F"+a.$("#couponFeature").attr("data-vpcpromoid")+"&redirectProtocol=&mode=&useRedirectOnSuccess=1";c.preventDefault()};
(function(){var d=(location.protocol==="https:"?"https://":"http://")+window.ue_furl+"/1/action-impressions/1/OP/vpc/promotion/",e=a.$("#couponFeature").attr("data-vpcpromoid"),f=a.$("#couponFeature").attr("data-vpcasin"),f="vpc_i_"+e+"_"+f+"_dp_db_";f+=b()?c()?"r":"nr":"nc";d=d+(f+":"+e)+"?marketplaceId="+window.ue_mid+"&requestId="+window.ue.rid+"&session="+window.ue_sid;(new Image).src=d})();a.$("#vpcButton").find(".a-button").click(f);a.$("#vpcButtonSns").find(".a-button").click(f)});g.when("A",
"jQuery","cf").execute(function(a,b){function c(a,c){b(a.currentTarget).addClass(n);u.addClass(i);b("#"+l).show();b(a.currentTarget).get(0).id.split(j);var d=m.get(0).getBoundingClientRect(),e,f;window.pageYOffset?(e=window.pageYOffset,f=window.pageXOffset):(document.compatMode||"")==="CSS1Compat"?(e=document.documentElement.scrollTop,f=document.documentElement.scrollLeft):(e=document.body.scrollTop,f=document.body.scrollLeft);e=d.bottom+e;d=d.left+f;c.popover&&c.popover.popover.$container.css({top:Math.floor(e)+
"px",left:Math.floor(d)+"px",width:s+"px"}).addClass(q)}function d(a){b(a.currentTarget).removeClass(n);u.removeClass(i);b("#"+l).hide()}function e(){b("a[id^="+j+"]").each(function(a,e){b(e).bind(r,c).bind(o,d)})}function f(){var a=document.createElement("div"),c=b(g),c=c.position().top+c.outerHeight();a.id=l;b(a).addClass(k).css({width:u.outerWidth(),height:b(p).outerHeight()-c,top:c}).bind("touchend click",function(){return!1});u.append(a)}var g="#twister_feature_div",p="#leftCol",j="vodd-button-",
k="twister-overlay",i="twister-popover-visible",q="burj-vodd-popover",l="twisterOverlay",n="highlighted",r="TwisterVODD.showPopup",o="TwisterVODD.hidePopup",s=404;b("a[id^="+j+"]");var m=b("#twister"),u=b("#actionPanel");b(".burj").length&&(f(),e())});g.when("A","a-popover","actionpanel-modified-popover","cf").execute(function(a,b,c){var d=a.$;d("#sns-frequency-button").length&&(new c("sns-frequency-dropdown-popover",d("#sns-frequency-button")),a.declarative("sns-frequency-update","click",function(a){var c=
a.$target.parents("li"),a=a.data.frequency;c.siblings().removeClass("sns-selected-frequency");c.addClass("sns-selected-frequency");d("#rcxOrdFreq").val(a);d("#sns-frequency-button-label").text(c.text());b.get("sns-frequency-dropdown-popover").hide()}),a.declarative("sns-frequency-dropdown-popover-close","click",function(){b.get("sns-frequency-dropdown-popover").hide()}))});g.when("jQuery","action-panel").execute(function(a,b){function c(){if(a("#chkMom").length){var c;a("#chkMom").is(":checked")?
(d.attr("action","/gp/mom/pipeline/view-signup/"),c="mom"):(d.attr("action",e),c="sns");b.setPanelState({mode:c})}}var d=a("#addToCart"),e=d.attr("action");a("#chkMom").change(function(){c()});c()});g.when("jQuery","ready").register("lux-btf-headings-burj",function(a){var b,c;b=a(".prestige_beauty.burj-body #session-sims-feature h2.a-carousel-heading").parent();c=a(".prestige_beauty.burj-body #session-sims-feature .a-column.a-span4.a-span-last.a-text-right");!a.isEmptyObject(b)&&!a.isEmptyObject(c)&&
(b.addClass("a-push2"),c.removeClass("a-span4"),c.addClass("a-span2"));b=a(".prestige_beauty.burj-body #purchase-sims-feature h2.a-carousel-heading").parent();c=a(".prestige_beauty.burj-body #purchase-sims-feature .a-column.a-span4.a-span-last.a-text-right");!a.isEmptyObject(b)&&!a.isEmptyObject(c)&&(b.addClass("a-push2"),c.removeClass("a-span4"),c.addClass("a-span2"));b=a(".prestige_beauty.burj-body #reviewContainer");c=a(".prestige_beauty.burj-body #reviewTopContainer h2");!a.isEmptyObject(b)&&
!a.isEmptyObject(c)&&(c.parent().remove(),b.prepend(c))});g.when("A","ready").execute(function(a){if(a.$("body").hasClass("prestige_beauty")||a.$("body").hasClass("amazon_elements")){var b=a.$("#nav-subnav");a.$(window).scrollTop()===0&&b.length&&a.$("html, body").delay(0).animate({scrollTop:b.offset().top},800)}})})})(function(){var g=window.AmazonUIPageJS||P,a=g.attributeErrors;return a?a("BurjDesktopAssets"):g}());
;/* DeliveryStatic */
(function(f){f.execute(function(){f.when("A","jQuery","ready").register("DeliveryCountdownComponent",function(f,a){function g(a,d,f,e,g){this.strings=a;this.asin=d;this.deliveryMessageSectionId=f;this.countdownElementId=e;this.secondsLeft=g;this.intervalHandle=null}window.DeliveryCountdownHandler=function(a){var d=a.strings,f=a.asin,e=a.deliveryMessageSectionId,l=a.fastCountdownElementId,j=a.cheapCountdownElementId;this.cheapCountdownTimer=this.fastCountdownTimer=null;this.start=function(a,c){if(a>
0)this.fastCountdownTimer=new g(d,f,e,l,a),this.fastCountdownTimer.start();if(c>0)this.cheapCountdownTimer=new g(d,f,e,j,c),this.cheapCountdownTimer.start()};this.stop=function(){if(this.fastCountdownTimer)this.fastCountdownTimer.stop(),this.fastCountdownTimer=null;if(this.cheapCountdownTimer)this.cheapCountdownTimer.stop(),this.cheapCountdownTimer=null}};g.prototype.start=function(){var a=this;this.intervalHandle=f.interval(function(){a&&a.updateCountdownText()},1E3)};g.prototype.stop=function(){this.intervalHandle&&
window.clearInterval(this.intervalHandle)};g.prototype.updateCountdownText=function(){this.secondsLeft--;if(this.secondsLeft>0){var c=Math.floor(this.secondsLeft/60),d=c%60,c=Math.floor(c/60),f=this.secondsLeft%60,e=this.strings.inNext,g=c>1?this.strings.hours:this.strings.hour,j=d>1?this.strings.minutes:this.strings.minute,k=f>1?this.strings.seconds:this.strings.second,h=this.strings.timeSeperator;a(this.countdownElementId).html(c>0&&d>0?c+h+g+h+d+h+j+h+e:c>0&&d===0?c+h+g+e:c===0&&d>0?d+h+j+e:f+
h+k+e)}else this.stop(),d="<a href='javacript:window.location.reload();'>"+this.strings.refreshTimeout+"</a>",a(this.deliveryMessageSectionId).html(d)}});f.when("A","jQuery","a-popover","ready").execute(function(k,a){function g(g){var D=!1,b=g.selectedAddressId,q=g.selectedObfuscatedId,s=g.selectedAddressLabel,v=g.selectedCountryCode,w=g.selectedZipCode,m=g.selectedState,t=g.selectedCity,u=g.selectedDistrict,n=g.addressPopover.name,R=g.addressPopover.type,o=g.isRecognized,Q=0,J=!1;this.init=function(){D||
(D=!0,F())};this.destroy=function(){k.off("a:popover:beforeShow:"+n,x);a(document).undelegate(e,"focus");a(document).undelegate(B,"click");a(document).undelegate(i,"click");a(document).undelegate(j+" input[type=radio]","click");a(document).undelegate(A,"click")};var F=function(){k.on("a:popover:beforeShow:"+n,x);a(document).delegate(e,"focus",function(){a(e).removeClass("a-form-error");a(l).addClass("a-hidden")});a(document).delegate(B,"click",function(){window.location.href="/gp/sign-in.html?ie=UTF8&useRedirectOnSuccess=1&path="+
window.location.pathname});a(document).delegate(i,"click",function(){var b=a(e).val();!b||!b.match(/^\d{5}$/)?K():L({countryCode:"US",zipCode:b},!0)});a(document).delegate(j+" input[type=radio]","click",function(){var c=a.parseJSON(a(this).val());if(c){var d=c.id;d!==b&&L({addressId:d,isDefaultShippingAddress:c.isDefault,addressLabel:c.label},!1)}});a(document).delegate(A,"click",function(){z()})},x=function(){J||z()},z=function(){o&&a.ajax({type:"POST",url:c,contentType:"application/x-www-form-urlencoded;charset=utf-8",
data:{currentAddressCount:Q,loadCount:r,selectedAddressId:b},dataType:"json",success:function(b){if(b){var c=b.loadedAddressCount;if(c>0){var d=b.html;d&&(a(j).html(d),a(E).removeClass("a-hidden"),a(h).addClass("a-hidden"),a(N).removeClass("a-hidden"),b.hasMore?a(A).removeClass("a-hidden"):a(A).addClass("a-hidden"),Q=c)}}J=!0},error:function(){}})},K=function(){a(e).addClass("a-form-error");a(l).removeClass("a-hidden")},L=function(c,g){a.ajax({type:"POST",url:d,contentType:"application/x-www-form-urlencoded;charset=utf-8",
data:c,dataType:"json",success:function(c){if(c.sembuUpdated){if(c=c.address)b=c.addressId,q=c.obfuscatedId,s=c.addressLabel,v=c.countryCode,w=c.zipCode,m=c.state,t=c.city,u=c.district,c="",c=s?s:(t?t+", ":"")+(m?m+" ":"")+w,a(G).html(c),g&&(a(j+" input[type=radio]:checked").attr("checked",!1),a(e).val(""));f.when(R).execute(function(a){a.get(n)&&a.get(n).hide()});I(p);I(y)}else c.isValidAddress||K()},error:function(){I(C)}})},I=function(a){k.trigger(a,{addressId:b,obfuscatedId:q,countryCode:v,zipCode:w,
state:m,city:t,district:u})}}var c="/gp/delivery/ajax/get-customer-address-list.html",d="/gp/delivery/ajax/address-change.html",i="#unifiedLocationAddrUpdate",e="#unifiedLocationAddrInput",l="#unifiedLocationInvalidInputAlert",j="#unifiedLocationAccountAddrList",E="#unifiedLocationTitleSelectAddress",h="#unifiedLocationTitleNoAddress",G="#unifiedLocationSelectedAddressText",A="#unifiedLocationSeeMore",N="#unifiedLocationSeeMoreDiv",B="#unifiedLocationSignIn",r=5,y="DeliveryAddressDropdown_OnAddressChange",
p="DeliveryAddressDropdown_OnSembuUpdateSuccess",C="DeliveryAddressDropdown_OnSembuUpdateFail";f.register("DeliveryAddressDropdown",function(){var a;return{init:function(c){a&&a.destroy();(a=new g(c)).init()}}})})})})(function(){var f=window.AmazonUIPageJS||P,k=f.attributeErrors;return k?k("DeliveryStatic"):f}());
;/* FreshDetailPageDesktopAssets */
(function(a){a.execute(function(){a.when("jQuery","ready").register("fresh-add-to-cart",function(b){return{init:function(){b("#addToCart").length&&b("#addToCart").submit(function(a){a.preventDefault();a=b("#addToCart").attr("action");b.ajax({type:"POST",url:a,data:b("#addToCart").serialize()})})}}})})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("FreshDetailPageDesktopAssets"):a}());
;/* DetailPageAlohaAssets */
(function(a){a.execute(function(){})})(function(){var a=window.AmazonUIPageJS||P,b=a.attributeErrors;return b?b("DetailPageAlohaAssets"):a}());